feat: Add Currency and InputCurrency components
BearStudio/start-ui pull request #61
Opened 2021-05-26 08:57 UTC by ivan-dalmet

2021-05-27 12:17 UTC, yoannfleurydev requested changes

2021-05-27 12:17 UTC, yoannfleurydev commented on src/components/TextCurrency/docs.stories.tsx
> +import { Stack, Code } from '@chakra-ui/layout';
```suggestion
import { Stack, Code } from '@chakra-ui/react';
```

2021-05-27 12:17 UTC, yoannfleurydev commented on src/components/InputCurrency/docs.stories.tsx
> +import { Stack, Code } from '@chakra-ui/layout';
```suggestion
import { Stack, Code } from '@chakra-ui/react';
```

2021-05-27 15:21 UTC, ivan-dalmet commented on src/components/InputCurrency/docs.stories.tsx
> +import { Stack, Code } from '@chakra-ui/layout';
Fixed :)

2021-05-28 16:46 UTC, yoannfleurydev approved these changes
I approve this PR. I didn't see anything wrong, 

I didn't checkout on my machine, so if you want we can check together on monday, else you can merge this if you are confident enough.

2021-05-31 13:34 UTC, merged