Feat/new checkboxes
BearStudio/start-ui pull request #93
Opened 2021-08-18 12:26 UTC by Rileran

## Description

Refactoring and adding features to the `FieldCheckboxes` component. 

- Same usage as before.
- New usage with composable components `FieldCheckboxesItem` and `FieldCheckboxesCheckAll` : 
  ```jsx
  <FieldCheckboxes
    name="colors"
    label="Colors"
    required="You need to check at least one color"
  >
    <Stack>
      <FieldCheckboxesCheckAll>All colors</FieldCheckboxesCheckAll>
      <Divider />
      <FieldCheckboxesItem value="red">Red</FieldCheckboxesItem>
      <FieldCheckboxesItem value="green">Green</FieldCheckboxesItem>
      <FieldCheckboxesItem value="blue">Blue</FieldCheckboxesItem>
    </Stack>
  </FieldCheckboxes>
  ```

You can checkout the associated story file for all usages.

## Performances

Value was managed using [zustand library](https://github.com/pmndrs/zustand) due to poor performances caused by re-rendering in a lot a `FieldCheckboxesItem`.

It also resolves issue #85.

2021-08-18 12:58 UTC, yoannfleurydev requested changes

2021-08-18 12:58 UTC, yoannfleurydev commented on src/components/FieldCheckboxes/docs.stories.tsx
> +};
![bitmoji](https://sdk.bitmoji.com/render/panel/9d438724-a1e5-44b9-9172-377503bbffe6-a1987ddb-a11e-49bc-8a9b-052f30b8f6ce-v1.png?transparent=1&palette=1&width=246)

2021-08-18 12:58 UTC, yoannfleurydev commented on src/components/FieldCheckboxes/index.tsx
> +        );
Is it possible to change `s`, `x`, and `v` for more explicit name please?

2021-08-18 13:34 UTC, yoannfleurydev approved these changes

2021-08-18 13:34 UTC, yoannfleurydev commented
I approved the source code for now. I have not tested locally for the moment.

2021-08-19 08:17 UTC, ivan-dalmet approved these changes

2021-08-24 09:18 UTC, merged